### ISSUE TITLE
NoMethodError: undefined method `new' for Mexbt::Account:Module

### ISSUE THREAD

**Issue by dsmontoya** [meXBT/mexbt-ruby#1]
I'm just trying to configure each instance, but can't even initialize an object

This is an example code:
https://gist.github.com/dsmontoya/0edb4e901bda3bc64c76

**Comment by williamcoates** [comment]
Could you tell me what version of the gem you are using or are you using the latest master?

**Comment by dsmontoya** [comment]
I have " gem 'mexbt' " in my Gemfile

**Comment by williamcoates** [comment]
What ruby version are you using?

**Comment by dsmontoya** [comment]
Sorry!

ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

**Comment by williamcoates** [comment]
I think you are using an old version of the gem. Try:

`bundle update mexbt`

You should see it install version 0.0.9. 

In the old version Mexbt::Account was a module, thus the error.

**Comment by dsmontoya** [comment]
Oh, You're totally right! Thanks!
